### ISSUE TITLE
[Issue] you are burn in a boat

### ISSUE THREAD

**Issue by sous-park** [nanite/TheObsidianBoat#3]
### Mod version

1.2.1-build.10+mc1.18.1.jar

### Forge mod loader version

39.0.14

### Repeatable?

- [X] Yes

### Link to log files

[23:53:16] [main/INFO]: ModLauncher running: args [--launchTarget, forgeclient, --fml.forgeVersion, 39.0.14, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, --username, sous_park, --version, 1.18.1 с Minecraft Forge 1.18.1-39.0.14, --gameDir, C:\Users\sous_park\AppData\Roaming\.minecraft, --assetsDir, C:\Users\sous_park\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, fa6301c3d0f54b8881336a80823aba34, --accessToken, ????????, --clientId, clientid, --xuid, auth_xuid, --userType, ELYBY, --versionType, modified]
[23:53:16] [main/INFO]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 17.0.1 by Eclipse Adoptium
[23:53:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/sous_park/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319! Service=ModLauncher Env=CLIENT
[23:53:17] [main/INFO]: Found mod file ObsidianBoat-1.2.1-build.10+mc1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\sous_park\AppData\Roaming\.minecraft\mods}
[23:53:17] [main/INFO]: Found mod file fmlcore-1.18.1-39.0.14.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@274872f8
[23:53:17] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.0.14.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@274872f8
[23:53:17] [main/INFO]: Found mod file mclanguage-1.18.1-39.0.14.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@274872f8
[23:53:17] [main/INFO]: Found mod file client-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@274872f8
[23:53:17] [main/INFO]: Found mod file forge-1.18.1-39.0.14-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@274872f8
[23:53:18] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.18.1 с Minecraft Forge 1.18.1-39.0.14, --gameDir, C:\Users\sous_park\AppData\Roaming\.minecraft, --assetsDir, C:\Users\sous_park\AppData\Roaming\.minecraft\assets, --uuid, fa6301c3d0f54b8881336a80823aba34, --username, sous_park, --assetIndex, 1.18, --accessToken, ????????, --clientId, clientid, --xuid, auth_xuid, --userType, ELYBY, --versionType, modified]
[23:53:24] [main/WARN]: Unrecognized user type: ELYBY
[23:53:24] [Render thread/WARN]: Assets URL 'union:/C:/Users/sous_park/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.18.1-20211210.034407/client-1.18.1-20211210.034407-srg.jar%2368!/assets/.mcassetsroot' uses unexpected schema
[23:53:24] [Render thread/WARN]: Assets URL 'union:/C:/Users/sous_park/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.18.1-20211210.034407/client-1.18.1-20211210.034407-srg.jar%2368!/data/.mcassetsroot' uses unexpected schema
[23:53:24] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=<null>]
[23:53:24] [Render thread/INFO]: Setting user: sous_park
[23:53:25] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[23:53:27] [modloading-worker-0/INFO]: Forge mod loading, version 39.0.14, for MC 1.18.1 with MCP 20211210.034407
[23:53:27] [modloading-worker-0/INFO]: MinecraftForge v39.0.14 Initialized
[23:53:29] [Render thread/INFO]: Narrator library for x64 successfully loaded
[23:53:29] [Render thread/INFO]: Reloading ResourceManager: Mod Resources, Default
[23:53:29] [modloading-worker-0/WARN]: Configuration file C:\Users\sous_park\AppData\Roaming\.minecraft\config\forge-client.toml is not correct. Correcting
[23:53:29] [modloading-worker-0/WARN]: Incorrect key client.forceSystemNanoTime was corrected from null to its default, false. 
[23:53:29] [modloading-worker-0/WARN]: Incorrect key client.disableStairSlabCulling was corrected from false to its default, null. 
[23:53:29] [modloading-worker-0/WARN]: Incorrect key client.zoomInMissingModelTextInGui was corrected from false to its default, null. 
[23:53:29] [modloading-worker-0/WARN]: Incorrect key client.forgeLightPipelineEnabled was corrected from true to its default, null. 
[23:53:29] [modloading-worker-0/WARN]: Incorrect key client.forgeCloudsEnabled was corrected from true to its default, null. 
[23:53:29] [modloading-worker-0/WARN]: Incorrect key client.selectiveResourceReloadEnabled was corrected from true to its default, null. 
[23:53:30] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[23:53:31] [Forge Version Check/INFO]: [forge] Found status: BETA_OUTDATED Current: 39.0.14 Target: 39.0.44
[23:53:43] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Динамики (High Definition Audio Device)
[23:53:43] [Render thread/INFO]: Sound engine started
[23:53:43] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[23:53:43] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[23:53:43] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[23:53:43] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[23:53:43] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[23:53:43] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[23:53:43] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[23:53:44] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[23:53:44] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[23:53:44] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[23:53:45] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[23:53:56] [Render thread/WARN]: Missing data pack mod:jei
[23:53:56] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:53:56] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:53:56] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:53:56] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:53:56] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:53:56] [Render thread/INFO]: Reloading ResourceManager: Default, forge-1.18.1-39.0.14-universal.jar, ObsidianBoat-1.2.1-build.10+mc1.18.1.jar
[23:53:59] [Render thread/INFO]: Loaded 7 recipes
[23:54:00] [Render thread/INFO]: Loaded 1143 advancements
[23:54:01] [Render thread/ERROR]: This world was saved with mod jei which appears to be missing, things may not work well
[23:54:01] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[23:54:02] [Render thread/WARN]: Missing data pack mod:jei
[23:54:02] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:54:02] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:54:02] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:54:02] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:54:02] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:54:02] [Render thread/INFO]: Reloading ResourceManager: Default, forge-1.18.1-39.0.14-universal.jar, ObsidianBoat-1.2.1-build.10+mc1.18.1.jar
[23:54:04] [Render thread/INFO]: Loaded 7 recipes
[23:54:04] [Render thread/INFO]: Loaded 1143 advancements
[23:54:05] [Render thread/ERROR]: This world was saved with mod jei which appears to be missing, things may not work well
[23:54:05] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[23:54:05] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=<null>]
[23:54:05] [Server thread/INFO]: Starting integrated minecraft server version 1.18.1
[23:54:05] [Server thread/INFO]: Generating keypair
[23:54:05] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:54:06] [Render thread/INFO]: Подготовка области возрождения: 0%
[23:54:06] [Render thread/INFO]: Подготовка области возрождения: 0%
[23:54:06] [Render thread/INFO]: Подготовка области возрождения: 0%
[23:54:09] [Render thread/INFO]: Подготовка области возрождения: 0%
[23:54:09] [Render thread/INFO]: Подготовка области возрождения: 0%
[23:54:09] [Render thread/INFO]: Подготовка области возрождения: 0%
[23:54:09] [Render thread/INFO]: Подготовка области возрождения: 0%
[23:54:09] [Render thread/INFO]: Подготовка области возрождения: 0%
[23:54:09] [Render thread/INFO]: Подготовка области возрождения: 1%
[23:54:10] [Render thread/INFO]: Подготовка области возрождения: 17%
[23:54:11] [Render thread/INFO]: Подготовка области возрождения: 33%
[23:54:11] [Render thread/INFO]: Подготовка области возрождения: 45%
[23:54:12] [Render thread/INFO]: Подготовка области возрождения: 70%
[23:54:12] [Render thread/INFO]: Подготовка области возрождения: 89%
[23:54:12] [Server thread/INFO]: Successfully initialized permission handler forge:default_handler
[23:54:12] [Render thread/INFO]: Time elapsed: 6734 ms
[23:54:12] [Server thread/INFO]: Changing simulation distance to 12, from 0
[23:54:13] [Netty Local Client IO #0/INFO]: Connected to a modded server.
[23:54:13] [Server thread/INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@3a22ecbd
[23:54:13] [Server thread/INFO]: sous_park[local:E:6bdb91bc] logged in with entity id 137 at (-0.5, 115.0, 10.5)
[23:54:13] [Server thread/INFO]: sous_park присоединился к игре
[23:54:14] [Render thread/INFO]: Loaded 55 advancements
[23:54:41] [Server thread/INFO]: [sous_park: Изменён блок в точке -15, 109, 17]
[23:54:41] [Render thread/INFO]: [CHAT] Изменён блок в точке -15, 109, 17
[23:54:42] [Server thread/INFO]: [sous_park: Изменён блок в точке -15, 109, 17]
[23:54:43] [Render thread/INFO]: [CHAT] Изменён блок в точке -15, 109, 17
[23:55:02] [Server thread/INFO]: [sous_park: Ваш режим игры изменён на Творческий режим]
[23:55:02] [Render thread/INFO]: [CHAT] Ваш режим игры изменён на Творческий режим
[23:55:17] [Server thread/INFO]: [sous_park: Ваш режим игры изменён на Режим выживания]
[23:55:17] [Render thread/INFO]: [CHAT] Ваш режим игры изменён на Режим выживания
[23:55:21] [Server thread/INFO]: sous_park решил поплавать в лаве
[23:55:21] [Render thread/INFO]: [CHAT] sous_park решил поплавать в лаве
[23:55:22] [Server thread/INFO]: Skipping update from removed player 'ServerPlayer['sous_park'/137, l='ServerLevel[Новый мир]', x=-0.95, y=100.27, z=5.05, removed=KILLED]'
[23:55:22] [Server thread/INFO]: Saving and pausing game...
[23:55:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Новый мир]'/minecraft:overworld
[23:55:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Новый мир]'/minecraft:the_nether
[23:55:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Новый мир]'/minecraft:the_end
[23:55:23] [Server thread/INFO]: Saving and pausing game...
[23:55:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Новый мир]'/minecraft:overworld
[23:55:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Новый мир]'/minecraft:the_nether
[23:55:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Новый мир]'/minecraft:the_end
[23:55:24] [Server thread/INFO]: sous_park lost connection: Отключение
[23:55:24] [Server thread/INFO]: sous_park покинул игру
[23:55:24] [Server thread/INFO]: Stopping singleplayer server as player logged out
[23:55:24] [Server thread/INFO]: Stopping server
[23:55:24] [Server thread/INFO]: Saving players
[23:55:24] [Server thread/INFO]: Saving worlds
[23:55:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Новый мир]'/minecraft:overworld
[23:55:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Новый мир]'/minecraft:the_nether
[23:55:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Новый мир]'/minecraft:the_end
[23:55:24] [Server thread/INFO]: ThreadedAnvilChunkStorage (Новый мир (42)): All chunks are saved
[23:55:24] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:55:24] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:55:24] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[23:55:25] [Render thread/INFO]: Stopping!

### Steps to reproduce the issue

go to nether
place the boat to lava
seat down
get a fire

### Description of the issue you are having

In 1.2.1-build.10+mc1.18.1.jar You burn when you are in a boat

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
I swear I fixed, I take a look latter

**Comment by EchoWhiskeyZero** [comment]
Hello, it's still broken for me in ObsidianBoat-1.2.1-build.10+mc1.18.1.jar

**Comment by UnRealDinnerbone** [comment]
New version should be out on curseforge soon that fixes this issue
